export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QUANTITY: "ADJUST_QUANTITY",
    CLEAR_CART: "CLEAR_CART",
    SET_SEARCH_QUERY: "SET_SEARCH_QUERY"
}